### ISSUE TITLE
Avoid using select inputs in collaboration forms

### ISSUE THREAD

**Issue by jsperezg** [podemos-info/decidim-collaborations#15]
Collaboration forms should use radio buttons, similar to what have been done to select the collaboration amout for the following inputs:

* Select periodicity
* Select payment method type
* Select existing payment method.

**Comment by leio10** [comment]
Just to ensure that is clear, payment method type selector and existing payment methods options should be mixed in the same selector, for example:
 * existing credit card 1
 * existing credit card 2
 * existing direct debit
 * new direct debit
 * new credit card

**Comment by jsperezg** [comment]
@leio10 For this issue I will integrate only the current functionality. As soon as we start retrieving payment methods for the current user it will appear in the UI as you suggest
