### ISSUE TITLE
Create module icon

### ISSUE THREAD

**Issue by leio10** [podemos-info/decidim-collaborations#2]

**Comment by jsperezg** [comment]
Please @leio10, let me know when is the icon read so we can integrate it.

**Comment by leio10** [comment]
Hi @jsperezg, I've a first version of the icon, but github doesn't allow me to upload SVGs here. Please, give me the folder and name where it should be and I'll upload there.

**Comment by jsperezg** [comment]
Hi @leio10 You need to replace the file icon.svg at folder app/assets/images/decidim/collaborations.

**Comment by leio10** [comment]
Done!
