### ISSUE TITLE
User collaboration status should not depends on user navigation

### ISSUE THREAD

**Issue by leio10** [podemos-info/decidim-collaborations#27]
Currently, user collaboration status changes to accepted or rejected when user navigates to `validate` page. This is done by the user when it clicks on the "continue" button. But the user can just close the window, and the collaboration will stay pending forever.

**Comment by jsperezg** [comment]
User collaborations are accepted by default. This workflow only applies to user collaborations made with a new credit card. The validate url is passed to census. The credit card payment gateway is the responsible software of calling it. It is not intended to be used by plain users.
